### ISSUE TITLE
unmatching gaussian parameters

### ISSUE THREAD

**Issue by erdmsen** [Fisdet/FISDeT#2]
i was trying to reproduce the results of an article...

Since it is well documented in the literature, i presumed first gaussian parameter should be 'mean' and second should be 'std. deviation' yet when i enter a term with parameters (0,10), it gave the result of a bell-shaped curve ranged from x=0 to x=10 (first image)

![Screenshot 2021-05-02 173208](https://user-images.githubusercontent.com/56255271/116817171-ccc24200-ab6d-11eb-806f-32524713cc20.png)

And also tried a second term with the given parameters (35,10) while the domain is 0-100. it resulted with an error:

![Screenshot 2021-05-02 173057](https://user-images.githubusercontent.com/56255271/116817233-02ffc180-ab6e-11eb-9d13-53fd7e4131db.png)

**Comment by Fisdet** [comment]
Dear Erdem,

 

thanks for your interest, the version you are using is old.

 

You will find the new version here:

https://github.com/Fisdet/FISDeT

 

In this new version the Gaussian membership function is not yet implemented. 

 

The error you reported occurs because the value of the first box must be smaller than the second.

 

Best regards,

FISDeT team

Da: Erdem Sen ***@***.***> 
Inviato: domenica 2 maggio 2021 16.53
A: Fisdet/FISDeT ***@***.***>
Cc: Subscribed ***@***.***>
Oggetto: [Fisdet/FISDeT] unmatching gaussian parameters (#2)

 

i was trying to reproduce the results of an article...

Since it is well documented in the literature, i presumed first gaussian parameter should be 'mean' and second should be 'std. deviation' yet when i enter a term with parameters (0,10), it gave the result of a bell-shaped curve ranged from x=0 to x=10 (first image)

 <https://user-images.githubusercontent.com/56255271/116817171-ccc24200-ab6d-11eb-806f-32524713cc20.png> 

And also tried a second term with the given parameters (35,10) while the domain is 0-100. it resulted with an error:

 <https://user-images.githubusercontent.com/56255271/116817233-02ffc180-ab6e-11eb-9d13-53fd7e4131db.png>

**Comment by erdmsen** [comment]
well, that's what i am trying to say. If it is a range on x-axis, yes the first parameter must be smaller, but it shouldnt be a range:  mathematically an x-axis range is unpractical to define a gaussian function, parameters should be mean and std. deviation respectively as it is in the literature.

ty for the response, i hope you will apply gaussian function to the new version soon and also hope you will consider this

**Comment by Fisdet** [comment]
Of course, in the new version we will apply the definition of the gaussian membership function correctly.

 

Best regards,

FISDeT team

 

Da: Erdem Sen ***@***.***> 
Inviato: mercoledì 5 maggio 2021 16.10
A: Fisdet/FISDeT ***@***.***>
Cc: FISDeT(Fuzzy Inference System Development Tool) ***@***.***>; Comment ***@***.***>
Oggetto: Re: [Fisdet/FISDeT] unmatching gaussian parameters (#2)

 

well, that's what i am trying to say. If it is a range on x-axis, yes the first parameter must be smaller, but it shouldnt be a range: mathematically an x-axis range is unpractical to define a gaussian function, parameters should be mean and std. deviation respectively as it is in the literature.

ty for the response, i hope you will apply gaussian function to the new version soon and also hope you will consider this
